---
title: "ISRL Chapter 6 Labs"
output:
  pdf_document: default
  html_document: default
---
# Chapter 6 Lab
# p244

## Best Subset Selection 

```{r}
library(ISLR)
#fix(Hitters)
names(Hitters)
```

```{r}
dim(Hitters)
sum(is.na(Hitters$Salary))
```
```{r}
Hitters=na.omit(Hitters)
dim(Hitters)
sum(is.na(Hitters))
```

```{r}
library(leaps)
regfit.full=regsubsets(Salary~.,Hitters)
summary(regfit.full)
```
```{r}
regfit.full=regsubsets(Hitters$Salary~., data=Hitters,nvmax=19)
reg.summary=summary(regfit.full) # All 19
reg.summary
```
```{r}
names(reg.summary)

```

```{r}
reg.summary$rsq
```

```{r}
par(mfrow=c(2,2))
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS", type="l")
plot(reg.summary$adjr2 ,xlab="Number of Variables ", ylab="Adjusted RSq",type="l")
which.max(reg.summary$adjr2)
points(11,reg.summary$adjr2[11], col="red",cex=2,pch=20)
```


```{r}
plot(reg.summary$cp ,xlab="Number of Variables ", ylab="Cp", type='l')
which.min(reg.summary$cp ) # [1] 10
points(10,reg.summary$cp [10],col="red",cex=2,pch=20)
which.min(reg.summary$bic ) #[1] 6
plot(reg.summary$bic ,xlab="Number of Variables ",ylab="BIC", type='l')
points(6,reg.summary$bic [6],col="red",cex=2,pch=20)
```

```{r}
plot(regfit.full,scale="r2")
plot(regfit.full,scale="adjr2")
plot(regfit.full,scale="Cp")
plot(regfit.full,scale="bic")
```

```{r}
coef(regfit.full ,6)
```

## Forward and Backward Stepwise Selection

```{r}
regfit.fwd=regsubsets(Salary~., data=Hitters,nvmax=19, method ="forward")
summary(regfit.fwd)
regfit.bwd=regsubsets(Salary~., data=Hitters,nvmax=19, method ="backward")
summary(regfit.bwd)
```

```{r}
coef(regfit.full ,7)
coef(regfit.fwd ,7)
coef(regfit.bwd ,7)
```

## Choosing Among Models Using the Validation Set Approach and Cross-Validation

```{r}
set.seed(1)
train=sample(c(TRUE,FALSE), nrow(Hitters), replace=TRUE)
test =(! train )
```

```{r}
regfit.best=regsubsets(Salary~.,data=Hitters[train,], nvmax =19)
test.mat=model.matrix(Salary~.,data=Hitters[test,])
```

```{r}
val.errors=rep(NA,19)
for(i in 1:19) {
  coefi=coef(regfit.best,id=i)
  pred=test.mat[,names(coefi)]%*%coefi
  val.errors[i]=mean((Hitters$Salary[test]-pred)^2) 
}
val.errors
```

```{r}
which.min(val.errors)
coef(regfit.best,10)
```

```{r}
# p249
predict.regsubsets = function (object, newdata, id,...) {
  form=as.formula(object$call [[2]])
  mat=model.matrix(form,newdata)
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}
```

```{r}
regfit.best=regsubsets(Salary~.,data=Hitters ,nvmax=19)
coef(regfit.best ,10)
```
```{r}
# p250
k=10
set.seed (1)
folds=sample(1:k,nrow(Hitters),replace=TRUE)
cv.errors=matrix(NA,k,19, dimnames=list(NULL, paste(1:19)))
```

```{r}
for(j in 1:k){
  best.fit=regsubsets(Salary ~. , data = Hitters[ folds != j, ], nvmax=19) 
  
  for(i in 1:19){                    
    pred=predict(best.fit,Hitters[folds==j,],id=i) 
    cv.errors[j,i]=mean((Hitters$Salary[folds==j]-pred)^2)

  }
}
mean.cv.errors=apply(cv.errors ,2,mean)
mean.cv.errors
```
```{r}
par(mfrow=c(1,1))
plot(mean.cv.errors ,type='b')
```

```{r}
reg.best=regsubsets (Salary~.,data=Hitters , nvmax=19)
coef(reg.best ,11)
```
