---
title: "ISLR Chapter 8 Lab 2 - Fitting Regression Trees"
output:
  html_document:
    toc: true
    depth: 2       
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

p327

```{r}
library(tree)
library(MASS)
```

## Regression tree
```{r}
set.seed(1)
train = sample(1:nrow(Boston), nrow(Boston)/2)
tree.boston=tree(medv ~ ., Boston, subset=train)
summary(tree.boston)
```
Fix the plot.new error. [StackOverFlow Answer](https://stackoverflow.com/questions/7154133/plot-new-has-not-been-called-yet)

## Plot the Unpruned Tree

```{r}
{plot(tree.boston)
text(tree.boston,pretty=0) # plot.new error
}
```

```{r}
cv.boston=cv.tree(tree.boston)
plot(cv.boston$size, cv.boston$dev, type='b')
```

## Prune the Tree

```{r}
prune.boston=prune.tree(tree.boston, best=5)

{plot(prune.boston)
text(prune.boston, pretty=0)
}
```
## Predict the Response for the Test Data with Unpruned Tree

```{r}
yhat <-  predict(tree.boston, newdata=Boston[-train ,])
boston.test.y <- Boston[-train, "medv"]
{plot(yhat, boston.test.y)
abline (0 ,1)
}
mean((yhat - boston.test.y)^2)
```

