---
title: "ISLR Q4.5 - Differences between LDA and QDA"
output:
  html_document:
    toc: true
    depth: 2    
---
[ISLR Home](../index.html)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Question

p169

We now examine the differences between LDA and QDA

(a) If the Bayes decision boundary is linear, do we expect LDA or QDA to perform better on the training set? On the test set?
(b) If the Bayes decision boundary is non-linear, do we expect LDA or QDA to perform better on the training set? On the test set?
(c) In general, as the sample size n increases, do we expect the test prediction accuracy of QDA relative to LDA to improve, decline, or be unchanged? Why?
(d) True or False: Even if the Bayes decision boundary for a given problem is linear, we will probably achieve a superior test er- ror rate using QDA rather than LDA because QDA is flexible enough to model a linear decision boundary. Justify your answer.

***

# Notes

LDA has a linear decision boundary. p 151

KNN makes no assumptions about the shape of its decision boundary

QDA assumes a quadratic decision boundary. p152

QDA performs better than KNN with limited training observations.
Because it makes assumptions about its decision boundary

LDA does best on linear. QDA does for modestly non-linear. p154

KNN does best for complicated decision boundaries

# Answers

## 5a) 

QDA on and Training because it will fit the data better, potentially overfitting

LDA Test because of higher variance for QDA on Test data.

## 5b) 

QDA on both. Explain!!!!!!

## 5c) 

For Test data, QDA will improve more with more training data.

## 5d) 

FALSE It will overfit training data, have higher variance on test data

