---
title: "ISLR Chapter 03 Notes - Linear Regression"
output:
  html_document:
    toc: true
    depth: 2    
---
[ISLR Home](../index.html)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Linear Regression

Machine Learning: Start with linear regression

“a very simple approach for supervised learning”

“widely used statistical learning method”

## House Prices

Square feet | Price 

$$Y \approx \beta_0 + \beta_1 X \;(3.1)$$
$$\hat{y} = \beta_0 + \beta_1 x \;(3.2)$$
$$RSS = e_1^2 + e_2^2 + \ldots + e_n^2 \;(3.3)$$
$$Y = \beta_0 + \beta_1 X + \epsilon \;(3.5)$$
$$Var(\hat{\mu}) = SE(\hat{\mu})^2 = \frac{\sigma^2}{n} \;(3.7)$$


$y = \beta_0 + \beta_1x$

$Y = \beta_0 + \beta_1 X + \epsilon$

y is called response or target 
x predictor

Once we know betas we can predict value of response 

Minimize the total error from each point to our line. 

Bend the line to fit better 


Simple Linear one variable 

“We typically assume that the error term is independent of X.”


# Multiple Linear Regression

p71

We usually have more than one predictor. 

$Y = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p + \epsilon \;\;(3.19)$

## Estimating the Coefficients

p72

$\hat{y} = \hat{\beta}_0 + \beta_1 X_1 + \cdots + \beta_p X_p + \epsilon \;\;(3.21)$

RSS = 

Choose $\beta$ to $\beta_p$ that minimizes RSS
p73

p75

## One: Is There a Relationship Between the Response and Predictors?

$H_0: \beta_1 = \beta_2 = \beta_3 = \ldots = \beta_p = 0$

$H_a: at least one $\beta_j \ne 0$

This hypothesis test is performed by computing the F-statistic,

$$F=\frac{(TSS - RSS)/p}{RSS/(n-p-1)} \;\;(3.23)$$


## VIF - Variance Inflation Factor

p102

$$VIF(\beta_j) = \frac{1}{1-R_{X_j}^2|X_{-j}}$$

##
